server:
  port: 8080

#jdbc
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3307/gmall?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

#mybatis\u914D\u7F6E
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true #\u6539\u914D\u7F6E\u5C31\u662F\u6307\u8BB2\u5E26\u6709\u4E0B\u5212\u7EBF\u7684\u8868\u5B57\u6BB5\u6620\u5C04\u4E3A\u9A7C\u5CF0\u683C\u5F0F\u7684\u5B9E\u4F53\u7C7B\u5C5E\u6027

#\u67E5\u770B\u6267\u884C\u7684sql\u65F6\u53EF\u4EE5\u5C06\u65E5\u5FD7\u7EA7\u522B\u8C03\u8282\u6210debug
logging:
  level:
    root: info
