server:
  port: 8087

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3307/gmall?characterEncoding=utf8&useSSL=false&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  dubbo:
    application: payment-web #在服务中的名称
    protocol:
      name: dubbo #dubbo协议的通讯名称
    registry:
      address: 192.168.109.3:2181 #zookeeper注册中心的地址
      protocol: zookeeper #zookeeper通讯协议的名称
    base-package: com.atguigu.gmall #dubbo服务的扫描路径
    consumer:
      timeout: 60000 #设置超时时间
      check: false #设置是否检查服务存在
  thymeleaf:
    cache: false #关闭thymeleaf缓存（热部署）
    mode: LEGACYHTML5  #松校验
  redis:
    host: 192.168.109.3 #redis链接地址
    port: 6379  #redis端口号
    database: 0 #redis数据库
    #password: root

#mybatis
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true #该配置是指将带有下划线的表字段映射为驼峰格式的实体类属性（true 开启）

logging:
  level:
    root: info

