server:
  port: 8076

#jdbc
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3307/gmall?characterEncoding=utf8&useSSL=false&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  dubbo:
    application: order-service #服务注册的名称
    protocol:
      name: dubbo #dubbo的通讯协议名称
    registry:
      address: 192.168.109.3:2181 #zookeeper注册中心的地址
      protocol: zookeeper #zookeeper的通讯协议的名称
    base-package: com.atguigu.gmall #dubbo的服务的扫描路径
  redis:
    host: 192.168.109.3 #redis链接地址
    port: 6379  #redis端口号
    database: 0 #redis数据库
    #password: root

#mybatis
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true #该配置是指将带有下划线的表字段映射为驼峰格式的实体类属性（true 开启）

#设置日志级别 debug可以查看sql语句
logging:
  level:
    root: info







